[build]
  command = "npm install && npm run build"  # Added build step
  functions = "netlify/functions"  # Updated functions directory

[functions]
  directory = "netlify/functions"  # Updated to match the build.functions
  node_bundler = "esbuild"
  included_files = ["models/**/*.js"]
  external_node_modules = ["mongoose"]

[functions.api]
  handler = "api.handler"  # Explicitly specify the handler
  timeout = 30

[[redirects]]
  from = "/api/docs/*"
  to = "/.netlify/functions/api/docs/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200