[build]
  command = "npm install"  # Removed the build step
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["models/**/*.js"]
  external_node_modules = ["mongoose"]

[functions.api]
  handler = "api.handler"
  timeout = 30

[[redirects]]
  from = "/api/docs/*"
  to = "/.netlify/functions/api/docs/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200