[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["models/**/*.js", "swagger/**/*.yaml"]
  external_node_modules = ["mongoose"]

[functions.api]
  handler = "api.handler"
  timeout = 30

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/api/docs"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/.netlify/functions/api/docs/:splat"
  status = 200
