[build]
  command = "npm install"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["models/**/*.js"]
  external_node_modules = ["mongoose"]
  timeout = "30s"

[[redirects]]
  from = "/api/docs/*"
  to = "/.netlify/functions/api/docs/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200