openapi: 3.0.0
info:
  title: Train Location API
  version: 1.0.0
  description: API for managing train location data

servers:
  - url: http://localhost:8888/.netlify/functions/api
    description: Local Netlify development server

paths:
  /train-locations/{trainId}/latest:
    get:
      summary: Get latest location for a train
      parameters:
        - in: path
          name: trainId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Latest train location
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainId:
                    type: string
                  latitude:
                    type: number
                    format: float
                  longitude:
                    type: number
                    format: float
                  name:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
        '404':
          description: Train location not found
        '500':
          description: Internal server error

  /update-location:
    post:
      summary: Update train location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - trainId
                - latitude
                - longitude
              properties:
                trainId:
                  type: string
                latitude:
                  type: number
                  format: float
                longitude:
                  type: number
                  format: float
      responses:
        '201':
          description: Location data saved successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /train-locations/{trainId}/latest:
    get:
      summary: Get latest location for a train
      parameters:
        - in: path
          name: trainId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Latest train location
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainId:
                    type: string
                  latitude:
                    type: number
                    format: float
                  longitude:
                    type: number
                    format: float
                  name:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
        "404":
          description: Train location not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    TrainLocation:
      type: object
      properties:
        trainId:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        name:
          type: string
